### ISSUE TITLE
A problem with open3d version

### ISSUE THREAD

**Issue by hanxysgg** [LMD0311/PointMamba#1]
A problem occurs when installing requirements.txt
```shell
ERROR: Could not find a version that satisfies the requirement open3d==1.10.0 (from versions: 0.14.1, 0.15.2, 0.16.0, 0.17.0, 0.18.0)
ERROR: No matching distribution found for open3d==1.10.0
```
OS: Ubuntu 18.04
python version: 3.9 (as required)
torch and cuda toolkit version also satisfy requirements.

So where can I get open3d 1.10.0? I only found version 0.18.0 on its official website.

**Comment by LMD0311** [comment]
Apologies for the inconvenience, there seems to be an error in `requirement.txt`. You may try `pip install open3d==0.18.0` as an alternative. I will fix this bug. Feel free to reach out with any problem!
