### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by hithqd** [LMD0311/PointMamba#11]
Thank you for your great work. I have two questions.

(1) I would like to ask what is the startup script and code for the test ?
Is that so？
`CUDA_VISIBLE_DEVICES=<GPU> python main.py --test --config cfgs/finetune_modelnet.yaml --ckpts <path/to/model> --exp_name <name>`

(2) The second question is about pre-training. 

![image](https://github.com/LMD0311/PointMamba/assets/37433515/1fade444-271a-4286-8c62-c0d79a25c245)
After the pre-training is completed, several models will be saved. Which one is the best? Is the one named ckpt-last.pth the best?

**Comment by LMD0311** [comment]
(1) Yes.

(2) Yes, we default to selecting the last checkpoint.
