### ISSUE TITLE
Excuse me, if this box is not checked, does it mean that the code for splitting and splitting has not been released yet?

### ISSUE THREAD

**Issue by OkLetsGoi** [LMD0311/PointMamba#13]
Excuse me, if this box is not checked, does it mean that the code for splitting and splitting has not been released yet?
![image](https://github.com/LMD0311/PointMamba/assets/148300443/85f2ea44-9724-4f6f-9328-a718815e457c)

**Comment by LMD0311** [comment]
Yes.

**Comment by OkLetsGoi** [comment]
请问什么时候能发布呢哥

**Comment by OkLetsGoi** [comment]
> Yes.
Excuse me, when will it be released?

**Comment by LMD0311** [comment]
We still working on it.

**Comment by LMD0311** [comment]
I am closing this issue. Please feel free to reopen it if necessary.
