### ISSUE TITLE
Problems when installing pointnet2_ops

### ISSUE THREAD

**Issue by xuanyuulin** [LMD0311/PointMamba#15]
When I tried to install pointnet2_ops, it met some problems below: 

Building wheels for collected packages: pointnet2_ops
  Building wheel for pointnet2_ops (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/pointnet2_ops
      copying pointnet2_ops/pointnet2_utils.py -> build/lib.linux-x86_64-cpython-39/pointnet2_ops
      copying pointnet2_ops/_version.py -> build/lib.linux-x86_64-cpython-39/pointnet2_ops
      copying pointnet2_ops/pointnet2_modules.py -> build/lib.linux-x86_64-cpython-39/pointnet2_ops
      copying pointnet2_ops/__init__.py -> build/lib.linux-x86_64-cpython-39/pointnet2_ops
      running egg_info
      creating pointnet2_ops.egg-info
      writing pointnet2_ops.egg-info/PKG-INFO
      writing dependency_links to pointnet2_ops.egg-info/dependency_links.txt
      writing requirements to pointnet2_ops.egg-info/requires.txt
      writing top-level names to pointnet2_ops.egg-info/top_level.txt
      writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
      reading manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
      creating build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src
      creating build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/ball_query.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/cuda_utils.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/group_points.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/interpolate.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/sampling.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      copying pointnet2_ops/_ext-src/include/utils.h -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/include
      creating build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/ball_query.cpp -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/ball_query_gpu.cu -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/bindings.cpp -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/group_points.cpp -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/group_points_gpu.cu -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/interpolate.cpp -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/interpolate_gpu.cu -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/sampling.cpp -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src
      running build_ext
      building 'pointnet2_ops._ext' extension
      creating /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39
      creating /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops 
      creating /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/
_ext-src
      creating /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/
_ext-src/src
      Emitting ninja build file /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-
39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      1.11.1.git.kitware.jobserver-1
      g++ -pthread -B /home/lxy/miniconda3/envs/pointmamba/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/lxy/miniconda3/envs/pointma
mba/lib -Wl,-rpath-link,/home/lxy/miniconda3/envs/pointmamba/lib -L/home/lxy/miniconda3/envs/pointmamba/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/lx
y/miniconda3/envs/pointmamba/lib -Wl,-rpath-link,/home/lxy/miniconda3/envs/pointmamba/lib -L/home/lxy/miniconda3/envs/pointmamba/lib /tmp/pip-install-4cxg7
72c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src/ball_query.o /tmp/pip-in
stall-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src/ball_query_gp
u.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/sr
c/bindings.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_e
xt-src/src/group_points.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/poi
ntnet2_ops/_ext-src/src/group_points_gpu.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_
64-cpython-39/pointnet2_ops/_ext-src/src/interpolate.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/tem
p.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src/interpolate_gpu.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_o
ps_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src/sampling.o /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/po
intnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_ops/_ext-src/src/sampling_gpu.o -L/home/lxy/miniconda3/envs/pointmamba/lib/python3.9/site-pack
ages/torch/lib -L/usr/local/cuda-11.7/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linu
x-x86_64-cpython-39/pointnet2_ops/_ext.cpython-39-x86_64-linux-gnu.so
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/ball_query.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/ball_query_gpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/bindings.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/group_points.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/group_points_gpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/interpolate.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/interpolate_gpu.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/sampling.o: 没有那个文件或目录
      g++: error: /tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/build/temp.linux-x86_64-cpython-39/pointnet2_o
ps/_ext-src/src/sampling_gpu.o: 没有那个文件或目录
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2_ops
  Running setup.py clean for pointnet2_ops
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4cxg772c/pointnet2-ops_88c1d8c48d974f3fbab744197ca37a19/pointnet2_ops_lib/setup.py", line 17, in <module>
          exec(open(osp.join("pointnet2_ops", "_version.py")).read())
      FileNotFoundError: [Errno 2] No such file or directory: 'pointnet2_ops/_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pointnet2_ops
Failed to build pointnet2_ops
ERROR: Could not build wheels for pointnet2_ops, which is required to install pyproject.toml-based projects

How can I figure out this problem, I will be very grateful for your reply.

**Comment by LMD0311** [comment]
Thank you for your interest in our work and apologies for the delay in response.

I have not encountered a similar issue, but you could consider updating the `pip` version.

**Comment by LMD0311** [comment]
I am closing this issue. Please feel free to reopen it if necessary.
