### ISSUE TITLE
Trying to backward through the graph a second time

### ISSUE THREAD

**Issue by HongweiDong84** [LMD0311/PointMamba#20]
"Why does it give the error 'Trying to backward through the graph a second time' at the position xyz1, xyz2, idx1, idx2 = ctx.saved_tensors after running? Is there something wrong with my setup? Could this be related to the versions of Chamfer Distance and EMD installed?"

**Comment by LMD0311** [comment]
Thank you for your interest! 

I haven’t encountered any related errors; you might try the environment mentioned in the repository.

**Comment by HongweiDong84** [comment]
Thank you!

**Comment by HongweiDong84** [comment]
> Thank you for your interest!
> 
> I haven’t encountered any related errors; you might try the environment mentioned in the repository.

I know that during installation, "KNN_CUDA" needs to be differentiated between Windows and Linux versions. So, do I need to differentiate between Windows and Linux versions when installing "Chamfer" and "PointNet++"?
