### ISSUE TITLE
windows reproduce 

### ISSUE THREAD

**Issue by HongweiDong84** [LMD0311/PointMamba#21]
Do you conduct experiments on Windows? If I need to reproduce the experiments on Windows, what modifications are necessary?

**Comment by LMD0311** [comment]
I apologize for not being able to give you more references. All experiments were performed on the Ubantu server.

**Comment by HongweiDong84** [comment]
I know that during installation, "KNN_CUDA" needs to be differentiated between Windows and Linux versions. So, do I need to differentiate between Windows and Linux versions when installing "Chamfer" and "PointNet++"?
