### ISSUE TITLE
Hello, I have another question. I see some codes related to testing in the code, but I don't see any commands for using the test. Does point cloud classification require testing? If so, can you tell me the command for the test?

### ISSUE THREAD

**Issue by JennyWow111** [LMD0311/PointMamba#24]
Hello, I have another question. I see some codes related to testing in the code, but I don't see any commands for using the test. Does point cloud classification require testing? If so, can you tell me the command for the test?

**Comment by LMD0311** [comment]
Apologies for the inconvenience. You can try this command:
`CUDA_VISIBLE_DEVICES=0 python main.py --config path/to/config --test --exp_name saving/dir/path --ckpts path/to/ckpt-best.pth
`

**Comment by JennyWow111** [comment]
Thank you so much!
