### ISSUE TITLE
Mamba blocks

### ISSUE THREAD

**Issue by Dreamxxxxxx** [LMD0311/PointMamba#26]
Hello, thank you very much for your excellent work. I have a question to ask you. In the legend of the paper, the point cloud features go through multiple MAMBA blocks, but in reality, the code implementation only goes through one blocks!
![image](https://github.com/user-attachments/assets/2290f032-a5d8-45c4-80e8-1a4e178de1dc)
![image](https://github.com/user-attachments/assets/996b4f87-8829-4b56-b183-f9fb7d5e7cfd)

**Comment by LMD0311** [comment]
You may forget the `for` loop here.
https://github.com/LMD0311/PointMamba/blob/da441cc374eed89d20be85887f08dd0bec3d619a/models/point_mamba.py#L206

**Comment by Dreamxxxxxx** [comment]
> You may forget the `for` loop here.
> 
> https://github.com/LMD0311/PointMamba/blob/da441cc374eed89d20be85887f08dd0bec3d619a/models/point_mamba.py#L206

Thank you very much for your prompt response. Please forgive my carelessness. I may not be familiar with MAMBA, but I will take a closer look.
