### ISSUE TITLE
Rotational augmentation

### ISSUE THREAD

**Issue by HongweiDong84** [LMD0311/PointMamba#27]
Here’s the English translation of your request:

"In the title of Table 1, you mentioned '† indicates that using simple rotational augmentation [11] for training.' How is this rotational augmentation implemented in the code? Additionally, I noticed that you also applied rotational augmentation to Point-MAE in Table 1. How is that part implemented? Thank you very much!"

**Comment by LMD0311** [comment]
please refer to `train_transforms` in `runner_finetune.py`
https://github.com/LMD0311/PointMamba/blob/da441cc374eed89d20be85887f08dd0bec3d619a/tools/runner_finetune.py#L22
