### ISSUE TITLE
Problems when installing Chamfer Distance

### ISSUE THREAD

**Issue by hanxysgg** [LMD0311/PointMamba#3]
os: Ubuntu 18.04
other requirements are all satisfied.
problems occured when installing Chamfer Distance.
![屏幕截图 2024-03-06 161546](https://github.com/LMD0311/PointMamba/assets/47966367/4b3884b5-7485-4010-8225-fce0b6353a30)
![屏幕截图 2024-03-06 161601](https://github.com/LMD0311/PointMamba/assets/47966367/6a3a2452-9d4a-49ce-bb7d-af60bb535065)
![屏幕截图 2024-03-06 161632](https://github.com/LMD0311/PointMamba/assets/47966367/e5a533ee-e0ea-4d03-9384-49137f019225)
![屏幕截图 2024-03-06 161651](https://github.com/LMD0311/PointMamba/assets/47966367/b2efd361-541f-48f1-886a-c78cb7c0ebd5)

Could anyone help me solve this?

**Comment by LMD0311** [comment]
Apologies for the inconvenience. Is the CUDA version currently set to 11.7? You can verify by using the command `nvcc -V`.

**Comment by LMD0311** [comment]
I re-cloned the repository and set up the environment on a different machine, and encountered no similar errors.

A while back, we discovered that a matching error could arise if the pytorch and cuda versions didn't align, but since you've already made the adjustment, I can't pinpoint the exact cause of the issue.

Running `python setup.py install --user --verbose` might offer more comprehensive error insights.

**Comment by hanxysgg** [comment]
> I re-cloned the repository and set up the environment on a different machine, and encountered no similar errors.
> 
> A while back, we discovered that a matching error could arise if the pytorch and cuda versions didn't align, but since you've already made the adjustment, I can't pinpoint the exact cause of the issue.
> 
> Running `python setup.py install --user --verbose` might offer more comprehensive error insights.

Thank you. I'm gonna try it.

**Comment by LMD0311** [comment]
`Chamfer Distance` is used for pre-training; you can comment out the relevant code, ignore this for now, and train from scratch or use the pre-trained weights we provide.

If you find a solution to this problem, please provide feedback! 🙏🙏🙏

**Comment by hanxysgg** [comment]
New problem:  should the version of causal-conv1d be <= 1.0.2?
I tried 1.2.0 and failed in the training from scratch of Part Segmentation on ShapeNetPart, but succeeded after installing causal-conv1d 1.0.2.




| |
cosmos00
|
|
***@***.***
|
---- Replied Message ----
| From | Xin ***@***.***> |
| Date | 3/6/2024 22:12 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [LMD0311/PointMamba] Problems when installing Chamfer Distance (Issue #3) |

Chamfer Distance is used for pre-training; you can comment out the relevant code, ignore this for now, and train from scratch or use the pre-trained weights we provide.

If you find a solution to this problem, please provide feedback! 🙏🙏🙏

**Comment by LMD0311** [comment]
This is the environment I utilize. You can locate the specific version in the file.

[requirements.txt](https://github.com/LMD0311/PointMamba/files/14523954/requirements.txt)
```
absl-py==2.1.0
accelerate==0.27.0
addict==2.4.0
ansi2html==1.9.1
astor==0.8.1
asttokens==2.4.1
attrs==23.2.0
Automat==22.10.0
blinker==1.7.0
buildtools==1.0.6
cachetools==5.3.2
calflops==0.2.9
causal-conv1d==1.1.1
ccimport==0.4.2
certifi==2023.11.17
chamfer==2.0.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
comm==0.2.1
ConfigArgParse==1.7
constantly==23.10.4
contextlib2==21.6.0
contourpy==1.2.0
cumm-cu117==0.4.11
cycler==0.12.1
dash==2.14.2
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
docopt==0.6.2
easydict==1.11
einops==0.7.0
emd-ext==0.0.0
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.1
filelock==3.10.0
fire==0.5.0
Flask==3.0.0
fonttools==4.47.0
fsspec==2023.12.2
furl==2.1.3
google-auth==2.27.0
google-auth-oauthlib==1.2.0
greenlet==3.0.3
grpcio==1.60.1
h5py==3.10.0
huggingface-hub==0.20.2
hyperlink==21.0.0
idna==3.6
importlib-metadata==7.0.1
importlib-resources==6.1.1
incremental==22.10.0
ipdb==0.13.13
ipython==8.18.1
ipywidgets==8.1.1
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
json-tricks==3.17.3
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
jupyter_core==5.7.1
jupyterlab-widgets==3.0.9
kiwisolver==1.4.5
KNN-CUDA @ https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl#sha256=809a43da2eed950c65ba15e355e8cdbf975b6a948dced1f02414f26aba586cd0
lark==1.1.9
mamba-ssm @ file:///data/xywang/workspace/Point-MAE/mamba
Markdown==3.5.2
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
nbformat==5.9.2
nest-asyncio==1.5.8
ninja==1.11.1.1
numpy==1.26.3
oauthlib==3.2.2
open3d==0.18.0
opencv-python==4.9.0.80
orderedmultidict==1.0.1
packaging==23.2
pandas==2.1.4
parso==0.8.3
pccm==0.4.11
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.1.0
plotly==5.18.0
pointnet2-ops @ git+https://github.com/erikwijmans/Pointnet2_PyTorch.git@b5ceb6d9ca0467ea34beb81023f96ee82228f626#subdirectory=pointnet2_ops_lib
portalocker==2.8.2
prettytable==3.9.0
prompt-toolkit==3.0.43
protobuf==4.25.1
psutil==5.9.7
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pybind11==2.11.1
Pygments==2.17.2
pyparsing==3.1.1
pyquaternion==0.9.9
python-dateutil==2.8.2
PythonWebHDFS==0.2.3
pytz==2023.3.post1
PyYAML==6.0.1
redo==2.0.4
referencing==0.32.1
regex==2023.12.25
requests==2.31.0
requests-oauthlib==1.3.1
responses==0.24.1
retrying==1.3.4
rpds-py==0.16.2
rsa==4.9
safetensors==0.4.1
schema==0.7.5
scikit-learn==1.3.2
scipy==1.11.4
simplejson==3.19.2
six==1.16.0
spconv-cu117==2.3.6
SQLAlchemy==2.0.25
stack-data==0.6.3
tenacity==8.2.3
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
termcolor==2.4.0
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
timm==0.4.5
tokenizers==0.15.0
tomli==2.0.1
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchstat==0.0.7
torchvision==0.14.1+cu117
tqdm==4.66.1
traitlets==5.14.1
transformers==4.36.2
transforms3d==0.4.1
triton==2.2.0
Twisted==23.10.0
typeguard==2.13.3
typing_extensions==4.9.0
tzdata==2023.4
urllib3==2.1.0
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.0.1
widgetsnbextension==4.0.9
zipp==3.17.0
zope.interface==6.1

```

**Comment by LMD0311** [comment]
You can use `causal-conv1d==1.1.1`.
