### ISSUE TITLE
Classification visualization: test_tsne function cannot output TSNE graph

### ISSUE THREAD

**Issue by L1277471578** [LMD0311/PointMamba#36]
Call the _test_tsne_ function in _runner_finetune.py_, error:

  File "/home/g512/liubin/PointMamba/tools/runner_finetune.py", line 625, in test_tsne
    test_only_tsne(base_model, test_dataloader, args, config, logger=logger)
  File "/home/g512/liubin/PointMamba/tools/runner_finetune.py", line 582, in test_only_tsne
    _, concat_f = base_model(points)
ValueError: too many values to unpack (expected 2)

I changed  _ , concat_f=base_comodel (points)  to **_`concat_f=base_comodel (points) [-2]`_**, new error:  

File "/home/g512/liubin/PointMamba/tools/runner_finetune.py", line 601, in test_only_tsne
test_feature = test_feature[index]
IndexError: The shape of the mask [2468] at index 0 does not match the shape of the indexed tensor [1560] at index 0

**Comment by L1277471578** [comment]
After calling the test_tsne function, an error occurred:

  File "/home/g512/liubin/PointMamba/tools/runner_finetune.py", line 625, in test_tsne
    test_only_tsne(base_model, test_dataloader, args, config, logger=logger)
  File "/home/g512/liubin/PointMamba/tools/runner_finetune.py", line 582, in test_only_tsne
    _, concat_f = base_model(points)
ValueError: too many values to unpack (expected 2)

I haven't modified test_tsne anywhere, does this mean that a certain parameter needs to be set?

**Comment by L1277471578** [comment]
Hello, I know _concat_f_ is a feature. 
Now, there are 39 _concat_f_, each shape is [40]; and there are 39 _label_, of which 38 shapes are [64],  one is [36]. 
The shape of the _test_feature_ formed by concatenating is [1560] (40 * 39), while the corresponding _test_label_ is [2468] (38 * 64+36=2468). 
I think the problem lies here. I don't know why the shape of the _label_ and _concat_f_ are different, and only the shape of the last _label_ is [36], while the others are [64]. I think the shape of _concat_f_ is correct because modelnet40 has 40 categories and the output shape is [40], which is reasonable. The question is why the _label_ are [64] and [36], and how should they be modified?
 I hope you can give me some advice, thank you very much!!
 This is the code for printing shapes and its output：
 
![391980522-08fee261-a266-4238-a576-de2ddcaa7849](https://github.com/user-attachments/assets/4a2bc0dd-0d5b-4c26-a1ff-5ba8949f1a31)

![391980560-ac1099ae-3b81-483b-b0c4-b5cb75b5544d](https://github.com/user-attachments/assets/20a1190c-edaa-4ecf-883b-dac84f57ddaf)

**Comment by L1277471578** [comment]
Change the code from line 547 to line 554 to the following：

```
        test_label = torch.cat(test_label, dim=0)
        test_feature = torch.cat(test_feature, dim=0)
        test_feature = test_feature.cpu().numpy()
        label = test_label.cpu().numpy()
```

**Comment by rabbit218218** [comment]
Hello, do you know how to visualize masks and reconstructions?Can you help me？

**Comment by LMD0311** [comment]
> Hello, do you know how to visualize masks and reconstructions?Can you help me？

You may refer to https://github.com/LMD0311/PointMamba/blob/ff34a07e9237c729bd05975a37ed592b025a7783/models/point_mamba.py#L628-L639

**Comment by rabbit218218** [comment]
However, when I set the parameter of "vis" to "True" and then execute the pre - training, an error occurs:

Traceback (most recent call last):
  File "/home/xi107552304043/PointMamba/tools/runner_pretrain.py", line 145, in run_net
    loss.backward()
AttributeError: 'tuple' object has no attribute 'backward'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xi107552304043/PointMamba/main.py", line 83, in <module>
    main()
  File "/home/xi107552304043/PointMamba/main.py", line 79, in main
    pretrain(args, config, train_writer, val_writer)
  File "/home/xi107552304043/PointMamba/tools/runner_pretrain.py", line 148, in run_net
    loss = loss.mean()
AttributeError: 'tuple' object has no attribute 'mean'

How can I solve it and visilize ret1 and ret2 successfully？

**Comment by QiWang233** [comment]
@L1277471578 Can you share your results and the whole code of this module？Thanks
