### ISSUE TITLE
A question about reported experimental results

### ISSUE THREAD

**Issue by Rfdfz** [LMD0311/PointMamba#4]
Hi, your work is excellent, but I have a question about the reported experimental results.
In the item "Training from scratch" in the Table 2 in your paper, according to my understanding, the architecture of "Transformer" and "Point-MAE" should be consistent, but why are there two different experimental results?

**Comment by LMD0311** [comment]
Thank you for your interest! Apologies for the confusion. As indicated in the table caption, the * signifies the results we replicated. In the "Training from scratch" section, PointMAE* represents our reproduced results, while Transformer indicates the results from the Point-BERT paper (which makes a difference in the citation).

**Comment by LMD0311** [comment]
I am closing this issue. If you have any more questions, please feel free to reopen it or create new issues. :)
