### ISSUE TITLE
What is the use of `inference_params` in Mamba and how to set it?

### ISSUE THREAD

**Issue by yxchng** [LMD0311/PointMamba#7]

**Comment by LMD0311** [comment]
It is used to switch the inference mode for mamba. It is specifically for iterative decoding: processing the prompt to store the states (similar to KV cache), and then using that to generate tokens one by one. You can refer to [generation.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/utils/generation.py) to understand how it is implemented.

In our implementation, you do not need to set it.

**Comment by yxchng** [comment]
Will it make inference faster? Do you use it in inference?

**Comment by LMD0311** [comment]
No.
