### ISSUE TITLE
关于部件分割和分类任务中的特征最大值池化问题

### ISSUE THREAD

**Issue by xinpuliu** [LMD0311/PointMamba#8]
作者您好，感谢你们开源的好工作。
对于下面的代码我有点疑问，面对经过多层mamba之后的特征矩阵（B,N,C），分类是对N进行了最大值池化，变成了（B,1,C）这个我可以理解，但是部件分割代码变成了对C进行了最大值（平均值）池化，变成了（B,N,1），请问这个怎么理解呢？
![image](https://github.com/LMD0311/PointMamba/assets/61619158/e4168ebf-fafa-43d3-86fc-10d0919c9d2c)

**Comment by LMD0311** [comment]
During segmentation, the `max pool` and `average pool` are utilized as global features, which are then concatenated with the point-wise feature (line 531).

Please refer to our paper or the Point-MAE paper for more details.

**Comment by xinpuliu** [comment]
同理，在我看来有图分类任务中，global特征的提取是可以理解的，即对1这个点数的维度做池化。

**Comment by LMD0311** [comment]
We simply follow Point-MAE for fair comparison, which is also used by other work.
https://github.com/Pang-Yatian/Point-MAE/blob/11f4c99f60e2f635e40d23ccaf21ec9aa42705ef/segmentation/models/pt.py#L279
![image](https://github.com/LMD0311/PointMamba/assets/104890257/0f7abe75-eb4a-481d-9fc6-801c3586dab2)

**Comment by xinpuliu** [comment]
ok thanks~

**Comment by LMD0311** [comment]
I am going to close this issue. Feel free to open another issue or reopen this one.
